import Head from 'next/head'
import { useEthers, useEtherBalance } from "@usedapp/core";
import { formatEther } from "@ethersproject/units";
import Container from '@mui/material/Container';

export default function Home() {
  const { activateBrowserWallet, account, deactivate } = useEthers()
  const accountBalance = useEtherBalance(account)

  function handleConnectWallet() {
    activateBrowserWallet();
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {account ? (
          <>
            <p>Saldo em ETH: {accountBalance ? formatEther(accountBalance) : ""}</p>
            <p>
              Conta: {account}</p>

            <button onClick={() => deactivate()}>
              Desconectar
            </button>
          </>

        ) :
          (
            <button className="mt-4 mx-5" onClick={handleConnectWallet}>
              Conectar carteira
            </button>
          )
        }

      </div>

    </Container>
  )
}
