import Head from 'next/head'
import Container from '@mui/material/Container';
import Navbar from 'components/Navbar'

export default function Home() {
  return (
    <Container style={{ marginTop: 64 }} className='p-4'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Navbar />

        <p> Ola mundo</p>
      </>

    </Container>
  )
}
